target("libxdmcp")
set_kind("static")
add_headerfiles("include/X11/Xdmcp.h")
add_includedirs("include")
add_includedirs(".")
add_files("*.c")
add_defines("HAVE_SYS_RANDOM_H=1")
add_defines("HAVE_GETENTROPY=1")