# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "**/*" ]
  pull_request:
    branches: [ "**/*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          version=$(cat gradle.properties | grep openminecraft.version= | sed s/openminecraft.version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          version=$(cat gradle.properties | grep openminecraft.version= | sed s/openminecraft.version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}

      - name: GraalVM Setup
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --scan

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: OpenMinecraft-v${{ env.VERSION }}-${{ env.LAST_COMMIT_SHA }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar

  build-nativeimage:
    name: Build Native Image
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          version=$(cat gradle.properties | grep openminecraft.version= | sed s/openminecraft.version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          version=$(cat gradle.properties | grep openminecraft.version= | sed s/openminecraft.version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: .

      - name: GraalVM Setup
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'

      - name: Build native image
        run: |
          ls
          native-image --enable-native-access=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:+ForeignAPISupport --features=com.primogemstudio.engine.NativeImageFeature --gc=G1 -jar openminecraft-v${{ env.VERSION }}-${{ env.LAST_COMMIT_SHA }}.jar

      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: OpenMinecraft-nativeimage-linux-v${{ env.VERSION }}-${{ env.LAST_COMMIT_SHA }}
          path: |
            ./openminecraft*
